runtime: custom
env: flex
threadsafe: true
network:
  session_affinity: true
automatic_scaling:
  max_num_instances: 2
env_variables:
  ROOT_URL: 
  MONGO_URL: 
  MAIL_URL:
skip_files:
- ^(.*/)?\.dockerignore$
- ^(.*/)?\yarn-error.log$
- ^(.*/)?\.git$
- ^(.*/)?\.hg$
- ^(.*/)?\.svn$
  
